### ISSUE TITLE
Plain text plists cannot be handled by the gem

### ISSUE THREAD

**Issue by eni9889** [ckruse/CFPropertyList#33]
The following plist:

```
{ Filter = { Bundles = ( "com.facebook.Messenger" ); }; }
```

Leads to the error:
```
CFFormatError: invalid XML: Start tag expected, '<' not found
	from /Users/egjoka/.rvm/gems/ruby-2.1.5/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbNokogiriParser.rb:25:in `rescue in load'
	from /Users/egjoka/.rvm/gems/ruby-2.1.5/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbNokogiriParser.rb:13:in `load'
	from /Users/egjoka/.rvm/gems/ruby-2.1.5/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbCFPropertyList.rb:348:in `load'
	from /Users/egjoka/.rvm/gems/ruby-2.1.5/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbCFPropertyList.rb:248:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /Users/egjoka/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

**Comment by ckruse** [comment]
Interesting, I didn't expect that someone would still have to deal with plain text plists. Will have a look at this today.

**Comment by anishsheela** [comment]
Let me know if a new version will be released. I am packaging the gem to debian, according to ITP https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=773725

**Comment by ckruse** [comment]
I added support for plain plists. Can you confirm that it works with latest HEAD? When confirmed I will release a new version.

**Comment by ckruse** [comment]
OK, just released a new version. It works after a lot of testing.
